In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [5]:
df=pd.read_csv('carprice.csv')
df

Year  percent
0     1       80
1     2       70
2     3       60
3     4       50
4     5       50
5     6       45

In [6]:
reg=linear_model.LinearRegression()
reg.fit(df[['Year']],df.percent)

LinearRegression()

In [7]:
plt.xlabel('Year')
plt.ylabel('Percent')
plt.scatter(df.Year,df.percent,color='Red',marker='+')
plt.plot(df.Year,reg.predict(df[['Year']]),color='blue')
plt.plot(df.Year,df.percent,color='blue')

In [8]:
reg.predict([[6]])

array([41.66666667])

In [9]:
reg.coef_

array([-7.])

In [10]:
reg.intercept_

83.66666666666667

In [11]:
reg.predict([[1]])

array([76.66666667])