In [1]:
#myChinaClassification.py
# read pg-161-165 scikit-learn-docs.pdf
import sklearn
from sklearn import datasets
from pprint import pprint 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


#my_categories = If None (default), load all the categories. If not None, list of category names to load (other categories ignored).
my_path = r'C:\Users\Student\Downloads\ChinaClassification\train'
#decode_error='strict'[{‘strict’, ‘ignore’, ‘replace’}, 

china_train = sklearn.datasets.load_files(  my_path, 
                                            description=None, 
                                            categories=None, 
                                            load_content=True, 
                                            shuffle=True, 
                                            encoding='utf-8', 
                                            decode_error='replace', 
                                            random_state=0 )

pprint(list(china_train.target_names))

['China', 'Not_China']


In [2]:
len(china_train.filenames)

4

In [3]:
pprint(china_train.data)

['Chinese Macao',
 'Tokyo Japan Chinese',
 'Chinese Chinese Shanghai',
 'Chinese Beijing Chinese']


In [4]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(china_train.data)
#print("X_train_counts =\n",X_train_counts)
X_train_counts.shape # num of docs, vocabulary size 
print(count_vect.get_feature_names()) # all tokens
print(X_train_counts.toarray())
print("X_train_counts =\n",X_train_counts)

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[0 1 0 1 0 0]
 [0 1 1 0 0 1]
 [0 2 0 0 1 0]
 [1 2 0 0 0 0]]
X_train_counts =
   (0, 3)	1
  (0, 1)	1
  (1, 2)	1
  (1, 5)	1
  (1, 1)	1
  (2, 4)	1
  (2, 1)	2
  (3, 0)	1
  (3, 1)	2


In [21]:
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape # num of docs, vocabulary size

(5, 8)

In [5]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape # num of docs, vocabulary size

(4, 6)

In [6]:
# Training a classifier
clf = MultinomialNB().fit(X_train_tfidf, china_train.target)

In [7]:
docs_new = ['Chinese Tokyo Japan']
X_new_counts = count_vect.transform(docs_new)
print("X_new_counts.toarray() =\n", X_new_counts.toarray())
print ("X_new_counts =\n", X_new_counts)

tfidf_transformer = TfidfTransformer()
X_new_tfidf = tfidf_transformer.fit_transform(X_new_counts)
print ("X_new_tfidf =\n", X_new_tfidf)

predicted = clf.predict(X_new_tfidf)
probability = clf.predict_proba(X_new_tfidf)
print ("probability =\n", probability)
print(clf.predict_log_proba(X_new_tfidf))
for doc, category in zip(docs_new, predicted):
        print('%r => %s' % (doc, china_train.target_names[category]))

X_new_counts.toarray() =
 [[0 1 1 0 0 1]]
X_new_counts =
   (0, 1)	1
  (0, 2)	1
  (0, 5)	1
X_new_tfidf =
   (0, 5)	0.5773502691896258
  (0, 2)	0.5773502691896258
  (0, 1)	0.5773502691896258
probability =
 [[0.61450413 0.38549587]]
[[-0.48693963 -0.95322479]]
'Chinese Tokyo Japan' => China
