In [18]:
#myChinaClassification.py
# read pg-161-165 scikit-learn-docs.pdf
import sklearn
from sklearn import datasets
from pprint import pprint 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


#my_categories = If None (default),
#load all the categories. If not None, list
#of category names to load (other categories ignored).
my_path = r'/Users/aminulmac/Desktop/ChinaClassification/train'
#decode_error='strict'[{‘strict’, ‘ignore’, ‘replace’}, 

china_train = sklearn.datasets.load_files(  my_path, 
                                            description=None, 
                                            categories=None, #load all category
                                            load_content=True, 
                                            shuffle=True, 
                                            encoding='utf-8', 
                                            decode_error='replace', 
                                            random_state=0 )

pprint(list(china_train.target_names))   ##name of folder inside train folder

['China', 'Not_China']


In [19]:
len(china_train.filenames)  #number of files in train folder

4

In [7]:
pprint(china_train.data)  #the content of files 
#under the  sub directory of train directory

['Chinese Macao',
 'Tokyo Japan Chinese',
 'Chinese Chinese Shanghai',
 'Chinese Beijing Chinese']


In [30]:
count_vect = CountVectorizer() 
# count_vect is the object of CountVectorizer


X_train_counts = count_vect.fit_transform(china_train.data) 
#exampe chinese word how many times 
#in each file this this
#type of all information in X_tarin count

print("X_train_counts =\n",X_train_counts) 
#content in X_train




X_train_counts =
   (0, 1)	1
  (0, 3)	1
  (1, 1)	1
  (1, 5)	1
  (1, 2)	1
  (2, 1)	2
  (2, 4)	1
  (3, 1)	2
  (3, 0)	1


In [31]:
X_train_counts.shape # num of docs, vocabulary size 

(4, 6)

In [43]:
print(count_vect.get_feature_names()) # all tokens

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']


In [44]:
print(X_train_counts.toarray())   #print in matrix type

[[0 1 0 1 0 0]
 [0 1 1 0 0 1]
 [0 2 0 0 1 0]
 [1 2 0 0 0 0]]


In [39]:
print("X_train_counts =\n",X_train_counts) 
#exampe chinese word how many times 
#in each file this this type of all information in X_tarin count

X_train_counts =
   (0, 1)	1
  (0, 3)	1
  (1, 1)	1
  (1, 5)	1
  (1, 2)	1
  (2, 1)	2
  (2, 4)	1
  (3, 1)	2
  (3, 0)	1


In [10]:
# TfidfTransformer Transform a count matrix 
#to a normalized tf or tf-idf representation

#Tf means term-frequency while tf-idf 
#means term-frequency times inverse document-frequency

tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
#tf_transformer object of TfidfTransformer 
X_train_tf = tf_transformer.transform(X_train_counts) 
#X_train_tf containts term-frequency
X_train_tf.shape # num of docs, vocabulary size

(4, 6)

In [45]:
#tf-idf means term-frequency times inverse document-frequency
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape # num of docs, vocabulary size

(4, 6)

In [41]:
# Training a classifier
clf = MultinomialNB().fit(X_train_tfidf, china_train.target)

In [49]:
docs_new = ['Chinese Tokyo Japan']
X_new_counts = count_vect.transform(docs_new)

#matrix type print
print("X_new_counts.toarray() =\n", X_new_counts.toarray())




X_new_counts.toarray() =
 [[0 1 1 0 0 1]]


In [48]:
print ("X_new_counts =\n", X_new_counts)      
#normal print file_no token_no and how many times

X_new_counts =
   (0, 1)	1
  (0, 2)	1
  (0, 5)	1


In [51]:
tfidf_transformer = TfidfTransformer()
X_new_tfidf = tfidf_transformer.fit_transform(X_new_counts) 


#tf-idf means term-frequency times inverse document-frequency
print ("X_new_tfidf =\n", X_new_tfidf)


X_new_tfidf =
   (0, 5)	0.5773502691896258
  (0, 2)	0.5773502691896258
  (0, 1)	0.5773502691896258


In [56]:

predicted = clf.predict(X_new_tfidf)
probability = clf.predict_proba(X_new_tfidf)


In [57]:
print ("probability =\n", probability)

probability =
 [[0.61450413 0.38549587]]


In [60]:
print("predicted =\n",clf.predict_log_proba(X_new_tfidf))


predicted =
 [[-0.48693963 -0.95322479]]


In [59]:
for doc, category in zip(docs_new, predicted):
        print('%r => %s' % (doc, china_train.target_names[category]))    
#docs_new content in which class in china or not china 

'Chinese Tokyo Japan' => China
